### ISSUE TITLE
quadsim issue

### ISSUE THREAD

**Issue by Omikaa** [Rwik2000/crazyswarm_DATT#1]
can't find <path to quadsim>/learning/BC_experts/MPPI. In DATT, there is no 'learning' folder in quadsim.

**Comment by Rwik2000** [comment]
Hey,

I am currently updating both the repos. It will be up by this weekend. 

Sorry for the delay. Thank you for your patience!

**Comment by Omikaa** [comment]
ok , thank you for your reply

**Comment by Rwik2000** [comment]
Hey,

Can you please check now and let me know.
DATT, MPPI and PID should work.

I will add support for L1 adaptation and RMA.

**Comment by Omikaa** [comment]
OK， I will try it.

**Comment by Omikaa** [comment]
I find that there is a mistake in uw_cf.py which is 
![image](https://github.com/Rwik2000/crazyswarm_DATT/assets/136170290/8cf4cb4d-814e-4c77-a95b-1b46ba33ab7e)
I have updated the DATT repo and DATT_crazyswarm, I have no idea there is a mistake.But I guess this code is mean to import DATT_config from DATT.configuration.
![image](https://github.com/Rwik2000/crazyswarm_DATT/assets/136170290/363b3268-591d-4065-822f-c176fdccda86)

**Comment by Rwik2000** [comment]
Can you please check now.
I forgot to add cf.py config file in the DATT repo.

Thanks for point out.

Let me know if you face any issue, and feel free to reopen the issue.

**Comment by Omikaa** [comment]
Thank you. Now I can correctly run the uw_cf.py in simulation. But it can't succeed in reality.
Usually, I should modify the hover_swarm.launch file and crazyflies.yaml file first. Then, open a terminal to launch the hover_swarm.launch to see cf in rviz. Finally, I can run scripts.
But, In DATT, should I also launch the hover_swarm file or custom_hover_swarm file.And what difference is between custom file and original file. Which one should I modify?
![image](https://github.com/Rwik2000/crazyswarm_DATT/assets/136170290/8dbe66ea-eba1-4724-972c-9a4ac1761313)

**Comment by Rwik2000** [comment]
I think I did not add this to readme,
you should launch the `custom_swarm.launch`

There are many differences. When you do `custom_swarm.launch`, internally it uses our custom lower level PID controller instead of the default mellinger controller

**Comment by Rwik2000** [comment]
Hey @Omikaa 
Were you able to run one of the DATT models?
Let me know if you face any issue.
